# TravisCI configuration for decodelabs/collections

language: 'php'
os:
    - 'linux'
dist: 'bionic'

php:
    - '7.4'
    - '7.3'
    - '7.2'

cache:
    directories:
        - '${HOME}/.composer/cache'

before_install:
    - 'composer validate --strict'

install:
    - 'composer update --no-interaction --prefer-dist'

script:
    - 'composer run-script analyze -- --no-interaction'
